# Generated by Django 5.2.3 on 2025-06-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_source_item_description_item_details_item_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sources',
            field=models.ManyToManyField(to='app.item_source'),
        ),
    ]
