# Generated by Django 5.2.3 on 2025-06-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_item_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': "stat d'objets",
                'verbose_name_plural': "stats d'objets",
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'objet', 'verbose_name_plural': 'objets'},
        ),
        migrations.AlterModelOptions(
            name='item_category',
            options={'verbose_name': "catégorie d'objets", 'verbose_name_plural': "catégories d'objets"},
        ),
        migrations.AlterModelOptions(
            name='item_source',
            options={'verbose_name': "source d'objets", 'verbose_name_plural': "sources d'objets"},
        ),
        migrations.AlterModelOptions(
            name='item_subcategory',
            options={'verbose_name': "sous-catégorie d'objets", 'verbose_name_plural': "sous-catégories d'objets"},
        ),
        migrations.AlterModelOptions(
            name='item_type',
            options={'verbose_name': "type d'objets", 'verbose_name_plural': "types d'objets"},
        ),
        migrations.AlterField(
            model_name='item',
            name='sources',
            field=models.ManyToManyField(blank=True, to='app.item_source'),
        ),
        migrations.AddField(
            model_name='item',
            name='stats',
            field=models.ManyToManyField(blank=True, to='app.item_stat'),
        ),
    ]
