# Generated by Django 5.2.3 on 2025-06-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_stat_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_stat',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
