# Generated by Django 5.2.3 on 2025-06-17 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item_stat_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_category',
            options={'ordering': ['name'], 'verbose_name': "catégorie d'objets", 'verbose_name_plural': "catégories d'objets"},
        ),
        migrations.AlterModelOptions(
            name='item_source',
            options={'ordering': ['name'], 'verbose_name': "source d'objets", 'verbose_name_plural': "sources d'objets"},
        ),
        migrations.AlterModelOptions(
            name='item_stat',
            options={'ordering': ['name', 'value'], 'verbose_name': "stat d'objets", 'verbose_name_plural': "stats d'objets"},
        ),
        migrations.AlterModelOptions(
            name='item_subcategory',
            options={'ordering': ['name'], 'verbose_name': "sous-catégorie d'objets", 'verbose_name_plural': "sous-catégories d'objets"},
        ),
        migrations.AlterModelOptions(
            name='item_type',
            options={'ordering': ['name'], 'verbose_name': "type d'objets", 'verbose_name_plural': "types d'objets"},
        ),
        migrations.CreateModel(
            name='Recipe_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
            ],
            options={
                'verbose_name': 'ingrédient',
                'verbose_name_plural': 'ingrédients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='app.item')),
                ('ingredients', models.ManyToManyField(blank=True, to='app.recipe_ingredient')),
            ],
        ),
    ]
