# Generated by Django 5.2.3 on 2025-06-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_recipe_options_alter_recipe_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='details',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stack',
        ),
    ]
