# Generated by Django 5.2.3 on 2025-06-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_source',
            name='type',
            field=models.CharField(blank=True, choices=[('CAVE', 'Caverne'), ('ENEMY_CAMP', 'Camp'), ('ENEMY_OUTPOST', 'Avant-poste'), ('LANDMARK', 'Landmark'), ('SHIPWRECK', 'Épaves'), ('TESTING_STATION', 'Station expérimentale'), ('HARVEST', 'Récole'), ('CRAFT', 'Fabrication')], null=True),
        ),
    ]
