# Generated by Django 5.2.3 on 2025-06-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_item_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_source',
            name='map',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_source',
            name='type',
            field=models.CharField(blank=True, choices=[('ENEMY_OUTPOST', 'Avant-poste'), ('ENEMY_CAMP', 'Camp'), ('CAVE', 'Caverne'), ('SHIPWRECK', 'Épaves'), ('CRAFT', 'Fabrication'), ('LANDMARK', 'Landmark'), ('MERCHANT', 'Marchand'), ('HARVEST', 'Récole'), ('TESTING_STATION', 'Station expérimentale')], null=True),
        ),
    ]
