# Generated by Django 5.2.3 on 2025-06-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_item_source_map_alter_item_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='landsraad',
            field=models.BooleanField(null=True),
        ),
    ]
