# Generated by Django 5.2.3 on 2025-07-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_item_landsraad'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='landsraad_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
