# Generated by Django 5.2.3 on 2025-09-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_item_landsraad_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('armor_stillsuit', models.BooleanField()),
                ('armor_heavy', models.BooleanField()),
                ('armor_light', models.BooleanField()),
                ('color_top', models.CharField(max_length=7)),
                ('color_right', models.CharField(max_length=7)),
                ('color_bottom', models.CharField(max_length=7)),
                ('color_left', models.CharField(max_length=7)),
            ],
        ),
    ]
