# Generated by Django 5.2.3 on 2026-03-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_skin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='item',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='workshop',
        ),
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item_type',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='armor_heavy',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='armor_light',
        ),
        migrations.RemoveField(
            model_name='skin',
            name='armor_stillsuit',
        ),
        migrations.DeleteModel(
            name='Item_Category',
        ),
        migrations.DeleteModel(
            name='Item_Source',
        ),
        migrations.DeleteModel(
            name='Item_Stat',
        ),
        migrations.DeleteModel(
            name='Item_SubCategory',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Item_Type',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Recipe_Ingredient',
        ),
    ]
